package Myapp.model;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 26 16:40:56 EET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AccountImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Name,
        Password,
        Phonenumber,
        Email,
        Verified,
        Type,
        AccountId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int NAME = AttributesEnum.Name.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int PHONENUMBER = AttributesEnum.Phonenumber.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int VERIFIED = AttributesEnum.Verified.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int ACCOUNTID = AttributesEnum.AccountId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AccountImpl() {
    }

    /**
     * @param accountId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer accountId) {
        return new Key(new Object[] { accountId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("Myapp.model.Account");
    }
}

